server:
  port: 8899
spring:
  application:
    name: Order Management Application
  datasource:
    url: jdbc:mysql://localhost:3306/fis_training?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12112001
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true



